kind: pipeline
type: docker
name: citest


steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: codesync
    path: /drone/sync
  commands:
  - sleep 1000
  - cp -rf /drone/src /drone/sync
  - docker ps -a
  - docker run --net host --rm --privileged --shm-size 100g --ulimit memlock=-1 --env MTHREADS_VISIBLE_DEVICES=all --pid=host -v /drone/src/src:/data/qiuyunlei --name test_ci12 dockerhub.kubekey.local/mt-ai/lm-qy2:add_sh sh -c "bash /data/ci/af_build.sh"


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: codesync
  host:
    path: /drone/src
