local docker = {
  name: 'docker',
  image: 'docker:dind',
  command: [
    '--insecure-registry=sh-harbor.mthreads.com',
    '--registry-mirror=https://docker.mirrors.ustc.edu.cn/',
  ],
  privileged: true,
  volumes: [
    {
      name: 'dockersock',
      path: '/var/run',
    },
  ],
  resources: {
    limits: {
      cpu: 16000,
      memory: '32GiB',
    },
  },
};

local build_image() = {
  name: '🖼',
  image: 'dockerhub.kubekey.local/mt-ai/lm-qy2:kuae_1.1_0420_train',
  pull: 'always',
  volumes: [
    {
      name: 'dockersock',
      path: '/var/run',
    },
  ],
  resources: { limits: { cpu: 16000, memory: '32GiB' } },
  commands: [
    'sleep 5 # give docker enough time to start',
	'ls',
  ],
};


local post(pipeline_name, trigger_branch, trigger_event, trigger_cron) = {
  kind: 'pipeline',
  type: 'docker',
  name: pipeline_name,
  services: [docker],
  // jobs in this pipeline
  steps: [
    build_image(),
  ],
  // condition to run this pipeline
  trigger: {
    branch: trigger_branch,
    event: trigger_event,
    cron: trigger_cron,
  },
  volumes: [
    {
      name: 'dockersock',
      temp: {},
    },
  ],
};

[
  post(pipeline_name='post-merge-jobs-by-push', trigger_branch='main', trigger_event='push', trigger_cron=''),
]
